### ISSUE TITLE
Authentication div does not properly resize itself

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#13]
The element looks fine on a full-size monitor, but when you resize the browser window or view it from a mobile device, it starts to fall apart. Its contents end up becoming squished together.
![screen shot 2018-06-29 at 8 06 52 am](https://user-images.githubusercontent.com/26909213/42074284-fe116d0e-7b73-11e8-9b29-0397f9f2879e.png)
![img_3557](https://user-images.githubusercontent.com/26909213/42074301-1c51ee1a-7b74-11e8-9038-5014b8ef2b85.JPG)

**Comment by y21** [comment]
Fixed in #25.
