### ISSUE TITLE
Implement the InstantClick library

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#16]
InstantClick is a JavaScript library that dramatically speeds up your website, making navigation effectively instant in most cases.
Latency is inevitable with today’s internet architecture, so InstantClick cheats by preloading links you are likely to click on.
You can view its repository [here.](https://github.com/dieulot/instantclick/)

This would be helpful because it means that the loading page would be seen less often, and obviously make navigation faster.

**Comment by y21** [comment]
The InstantClick library has been implemented into the `clans` page, but not on other pages yet such as the main menu, login page, ...
**Note:** it embeds the library through HTTP, therefore browsers might block the request.
