### ISSUE TITLE
Add a "No thanks, play as a guest" button to the login and registration page

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#20]
This would be nice because some users do not want to log in.

**Comment by y21** [comment]
Umm... #10?

**Comment by DatNightcat** [comment]
This was added in commit https://github.com/blobs-io/blobs.io/commit/6a3fe4bed080b3038556623bf2ac4292a150297c. The button looks like this, and is placed under the `#auth` div:
![screenshot 2018-10-25 at 10 01 49 am](https://user-images.githubusercontent.com/26909213/47506579-60e51d00-d83e-11e8-8675-894c938d89e9.png)
However, the button does not actually function when pressed. See issue #10 for more details.
