### ISSUE TITLE
Mobile Controller Buttons

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#30]
**Is your feature request related to a problem? Please describe.**
The game is completely unplayable on mobile.

**Describe the solution you'd like**
I want there to be four directional buttons in the bottom-left corner, and the nom button in the bottom-right corner.

**Comment by y21** [comment]
Having buttons for mobile users would indeed be useful especially if the user does not have a keyboard, but I would prefer the movement buttons to be in the bottom right corner instead. Perhaps we could let the user decide on what side which buttons should be?

**Comment by DatNightcat** [comment]
Mobile controller buttons were added in commit f3bf71b1809e0db8b08381a8b614ab4fcccf8554.
