### ISSUE TITLE
Guests don’t show up in ‘x online’

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#33]
**Describe the bug**
When a guest is playing, they don’t count in the “x online” on the login page.

**To Reproduce**
1. Go to http://blobs-io.glitch.me/login/
2. Click on “Play as guest” to start playing
3. Go to http://blobs-io.glitch.me/login/ on a new tab or another device
4. The “x online” will be the same

**Expected behavior**
When a guest is playing, the “x online” counter should increase by 1.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 11.2.1
 - Browser: DuckDuckGo Privacy Browser
 - Version: 7.12.0 (uses WebKit 604.4.7)

**Comment by y21** [comment]
https://github.com/blobs-io/blobs.io/blob/6779894c453689ce29aa04a4ba98a85158a4aaa7/backend/server.js#L119

This line causes to only return the amount of users that are in the lobby. To fix this bug we need to concatenate the sockets array with the FFA players array and return the length.

**Comment by y21** [comment]
Fixed in https://github.com/blobs-io/blobs.io/commit/e12e122d31f5a9f8209d87ff45731a2264994e21.
