### ISSUE TITLE
Set default BR value higher than 0

### ISSUE THREAD

**Issue by y21** [blobs-io/blobs.io#35]
**Is your feature request related to a problem? Please describe.**
Currently the default BR value (blob rating you start with) is 0 and it would take way too long to get to silver even if you are very good at the game. 

**Describe the solution you'd like**
Let users start with 1000 BR so if you're good enough you can easily get to silver with a few noms.

**Describe alternatives you've considered**
We could set the default BR lower or higher than 1000, but 0 is definitely too low.

**Comment by DatNightcat** [comment]
The default BR value is now `1000`.
