### ISSUE TITLE
Proposal for blobs.io

### ISSUE THREAD

**Issue by leonardoderoy** [blobs-io/blobs.io#4]
Hello! @blobs-io

I'm a graphic designer and I like to support your project because I believe a good logo that reflects your project at its best can help the project publicity and trustability, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by y21** [comment]
Hello! 
First of all, thanks for your request. We just started this project about three or four days ago and we would really need some graphic designers over here.
Feel free to join our discord server: https://discord.gg/xQdDvq

**Comment by leonardoderoy** [comment]
Hello @blobs-io
I've joined the discord server but I'd rather to keep the conversation public through this issue, I'd like you to explain me with your own words and describe me the project to get the work done faster, thanks.

**Comment by y21** [comment]
Oh, I just thought this issue was some sort of spam, so I closed it. 
We didn't plan much on it yet but it will (obviously, as the "project" title says) be about blobs and similar to the game agar.io where you have to eat other cells. 
We would probably need some people who could design blobs.

**Comment by leonardoderoy** [comment]
Hi @y21
ok I will be happy to help me make a proposal for a possible logo.

**Comment by leonardoderoy** [comment]
Hi @y21  @blobs-io  Here is my initial design. Please let me know if you have suggestions in mind so that i can edit. thanks!

**Comment by leonardoderoy** [comment]
![image](https://user-images.githubusercontent.com/40496274/42119940-9d9ca976-7be0-11e8-9979-e2cfb3567df5.png)

**Comment by y21** [comment]
Hello,
thanks a lot for your submittion. We really appreciate your work and it is very good, but I should probably have been clearer with "blobs". 
You can take a look in the directory `public/assets` for examples. Also you probably know these blobs from google (especially if you're an android user).
If you have a question or anything, feel free to ask.

**Comment by DatNightcat** [comment]
![blobowo](https://user-images.githubusercontent.com/26909213/42131490-b2b979a2-7d0b-11e8-9fc8-0639f963e591.png)
![blobpeek](https://user-images.githubusercontent.com/26909213/42131489-b29834d6-7d0b-11e8-8674-d0e65719e418.png)

**Comment by leonardoderoy** [comment]
oh i see now. i will fix it and let you know @y21 @DatNightcat

**Comment by y21** [comment]
Alright.

**Comment by leonardoderoy** [comment]
here its ready @y21 @DatNightcat tell me if you like it ![blobs iologo](https://user-images.githubusercontent.com/40496274/42197656-d966b2bc-7e51-11e8-9654-b3a62af87b26.jpg)

**Comment by DatNightcat** [comment]
Very good! I really like the second one with the black background.

**Comment by leonardoderoy** [comment]
Hi @y21  no problem whatsoever, who wants to upload the pull requests

**Comment by y21** [comment]
Hello, sorry for the late response. We both (Nightcat and me) had a lot of stuff to do and couldn't spend a single minute into this project.
Apparently those images are too small and we can't use them as logo. Do you have them in bigger?

**Comment by y21** [comment]
Hello,
since you haven't replied in almost 3 months I'm closing this.
