### ISSUE TITLE
Implement function for better prompts

### ISSUE THREAD

**Issue by y21** [blobs-io/blobs.io#44]
**Is your feature request related to a problem? Please describe.**
The default `prompt()` function does not really fit into the design of blobs.io as it relies on the browser and also there's only a text box so can't input more than that.

**Describe the solution you'd like**
Instead it would be cool if we had a function that adds a centered HTML element that overrides all other HTML elements (`z-index`).

**Comment by DatNightcat** [comment]
I’d like this because they don’t show up in my preferred mobile browser- only in Safari do they work for me.

**Comment by y21** [comment]
DatNightcat Yes, that's true.

(...) as it relies on the browser


Also you cannot copy texts from alerts in some browsers, e.g. in Chrome on Android.
