### ISSUE TITLE
Unclutter the News section

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#49]
**Is your feature request related to a problem? Please describe.**
The only news on the page currently takes up a lot of space.
![cluttered news](https://user-images.githubusercontent.com/26909213/49594114-2b564800-f943-11e8-8908-98f4ca8f8ec0.png)

**Describe the solution you'd like**
Add an unordered list that contains links to the news. This could just be a popup or take you to another page.

**Describe alternatives you've considered**
You could move the news into a button that displays a popup with all of the news.

**Additional context**
![uncluttered news](https://user-images.githubusercontent.com/26909213/49594276-825c1d00-f943-11e8-8a7e-9dce664bd1eb.png)

**Comment by y21** [comment]
Yeah I don't want a separate page for news and the news section has a scrollbar once it contains a lot of content. But we could let the user "hide" articles when clicking on the headline.

**Comment by y21** [comment]
News section has been removed as news will be posted on the subreddit since the rewrite has been merged. I might add a page that gets news from the subreddit using the API later on.
