### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by SafelySwift** [blobs-io/blobs.io#73]
**Describe the bug**
The blobs do not collide with the bricks

**To Reproduce**
1. Try to collide with the bricks

**Expected behavior**
If I am not mistaken the bricks are supposed to be obstacles

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari

**Additional context**
I am not sure if this is expected behavior.

**Comment by y21** [comment]
Hello,
thank you for your bug report. We recently introduced these bricks and blobs indeed do not collide with them. 
In the games' final state we want there to be multiple types of brick walls. One of them being static/fixed walls, you cannot interact with them. 
The other type being peekable brick walls. Blobs can interact with them by pressing a specific key. "Peeking" (basically hiding behind walls) will charge a boost that you can use to be faster.

**Comment by y21** [comment]
Blobs now collide with walls.
