### ISSUE TITLE
{{ username }} and 1000 BR placeholders temporarily show up on main menu

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#8]
When the page loads, these placeholders temporarily show up.
![screen shot 2018-06-28 at 10 19 39 pm](https://user-images.githubusercontent.com/26909213/42058152-2c11ead6-7b28-11e8-9565-cb154c81d478.png)

**Comment by DatNightcat** [comment]
You mean me?
![blobowo](https://user-images.githubusercontent.com/26909213/42058034-bcaa0cbe-7b27-11e8-9d00-b8a24cd397c8.png)

**Comment by y21** [comment]
Nah, you do #9. 
![blobevil](https://user-images.githubusercontent.com/30553356/42058316-5536a58a-7b20-11e8-811f-768766bdcf61.png)

**Comment by y21** [comment]
Bug has been fixed. See #11.
