### ISSUE TITLE
Blob Health Regeneration

### ISSUE THREAD

**Issue by DatNightcat** [blobs-io/blobs.io#85]
**Is your feature request related to a problem? Please describe.**
Right now, blobs do not regenerate health. This probably makes them into sad, depressed blobs.

**Describe the solution you'd like**
Make blobs regenerate health under certain conditions.

**Comment by y21** [comment]
Good idea, any ideas on how much per second?

**Comment by y21** [comment]
Added. Blobs now generate 5 HP every 5 seconds.
